[package]
name = "mysql-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.3"
mysql_async = "0.32.1"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }
env_logger = "0.10.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_yaml = "0.9.14"